### ISSUE TITLE
2021.11.0 Beta Breaks Card - Doesn't Show Sensors

### ISSUE THREAD

**Issue by julianrinaldi** [benct/lovelace-xiaomi-vacuum-card#84]
In 2021.11.0 Beta, the sensors for the Xiaomi vacuum card have changed, due to the addition of the new non-primary/diagnostic entities. I figure this is already known, but I figured I'd make an issue for it.

**Comment by jscherry** [comment]
Same problem after installing 2021.11 beta all versions. Attributes are now sensors I believe.

**Comment by pedrolamas** [comment]
Confirming issue on latest version of Home Assistant 2021.11, as part of the [breaking changes](https://www.home-assistant.io/blog/2021/11/03/release-202111/#breaking-changes) (check the "Xiaomi Miio" changes, seems the attributes are now separate sensors)

**Comment by bellini666** [comment]
Was coming here to say that :)

**Comment by mcavarano** [comment]
Additionally for anyone who didn't read the breaking changes the sensors that are now missing for this card are disabled by default so you will need to manually enable them. 
Hopefully this is a simple fix to get the card functional again

**Comment by kimme1024** [comment]
> Additionally for anyone who didn't read the breaking changes the sensors that are now missing for this card are disabled by default so you will need to manually enable them.
> Hopefully this is a simple fix to get the card functional again

sadly it isn't...
also enabling them and renaming them under attributes when configuring the card doesn't help.
waiting for a solution for this as well...

**Comment by pedrolamas** [comment]
Not ideal, but I found a way to get it back working (though I don't expect this to be 100%) by using a template vacuum:

In the above I am using the `vacuum.roborock_vacuum_s6` and all new sensors around it to create a `vacuum.roborock_vacuum_s6_fix`:

```yaml
vacuum:
  - platform: template
    vacuums:
      roborock_vacuum_s6_fix:
        friendly_name: Limpinho
        value_template: >-
          {{ states('vacuum.roborock_vacuum_s6') }}
        battery_level_template: >-
          {{ state_attr('vacuum.roborock_vacuum_s6', 'battery_level') }}
        fan_speed_template: >-
          {{ state_attr('vacuum.roborock_vacuum_s6', 'fan_speed') }}
        attribute_templates:
          main_brush_left: >-
            {{ int(states('sensor.roborock_vacuum_s6_main_brush_left') | int / 3600) }}
          side_brush_left: >-
            {{ int(states('sensor.roborock_vacuum_s6_side_brush_left') | int / 3600) }}
          filter_left: >-
            {{ int(states('sensor.roborock_vacuum_s6_filter_left') | int / 3600) }}
          sensor_dirty_left: >-
            {{ int(states('sensor.roborock_vacuum_s6_sensor_dirty_left') | int / 3600) }}
          status: >-
            {{ state_attr('vacuum.roborock_vacuum_s6', 'status') }}
        fan_speeds: ["Silent", "Standard", "Medium", "Turbo", "Gentle", "Auto"]
        start:
          - service: vacuum.start
            target:
              entity_id: vacuum.roborock_vacuum_s6
        pause:
          - service: vacuum.pause
            target:
              entity_id: vacuum.roborock_vacuum_s6
        stop:
          - service: vacuum.stop
            target:
              entity_id: vacuum.roborock_vacuum_s6
        return_to_base:
          - service: vacuum.return_to_base
            target:
              entity_id: vacuum.roborock_vacuum_s6
        clean_spot:
          - service: vacuum.clean_spot
            target:
              entity_id: vacuum.roborock_vacuum_s6
        locate:
          - service: vacuum.locate
            target:
              entity_id: vacuum.roborock_vacuum_s6
        set_fan_speed:
          - service: vacuum.set_fan_speed
            target:
              entity_id: vacuum.roborock_vacuum_s6
```

This is not an ideal solution, and the best way going forward is to change the plugin to support the new way of working!

**Comment by julianrinaldi** [comment]
Dammit. I have 6 Roborock S6. That’s going to be a lot of clicking to enable those entities.

**Comment by bellini666** [comment]
> Not ideal, but I found a way to get it back working (though I don't expect this to be 100%) by using a template vacuum:
> 
> In the above I am using the `vacuum.roborock_vacuum_s6` and all new sensors around it to create a `vacuum.roborock_vacuum_s6_fix`:
> 
> ```yaml
> vacuum:
>   - platform: template
>     vacuums:
>       roborock_vacuum_s6_fix:
>         friendly_name: Limpinho
>         value_template: >-
>           {{ states('vacuum.roborock_vacuum_s6') }}
>         battery_level_template: >-
>           {{ state_attr('vacuum.roborock_vacuum_s6', 'battery_level') }}
>         fan_speed_template: >-
>           {{ state_attr('vacuum.roborock_vacuum_s6', 'fan_speed') }}
>         attribute_templates:
>           main_brush_left: >-
>             {{ int(states('sensor.roborock_vacuum_s6_main_brush_left') | int / 3600) }}
>           side_brush_left: >-
>             {{ int(states('sensor.roborock_vacuum_s6_side_brush_left') | int / 3600) }}
>           filter_left: >-
>             {{ int(states('sensor.roborock_vacuum_s6_filter_left') | int / 3600) }}
>           sensor_dirty_left: >-
>             {{ int(states('sensor.roborock_vacuum_s6_sensor_dirty_left') | int / 3600) }}
>           status: >-
>             {{ state_attr('vacuum.roborock_vacuum_s6', 'status') }}
>         fan_speeds: ["Silent", "Standard", "Medium", "Turbo", "Gentle", "Auto"]
>         start:
>           - service: vacuum.start
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
>         pause:
>           - service: vacuum.pause
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
>         stop:
>           - service: vacuum.stop
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
>         return_to_base:
>           - service: vacuum.return_to_base
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
>         clean_spot:
>           - service: vacuum.clean_spot
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
>         locate:
>           - service: vacuum.locate
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
>         set_fan_speed:
>           - service: vacuum.set_fan_speed
>             target:
>               entity_id: vacuum.roborock_vacuum_s6
> ```
> 
> This is not an ideal solution, and the best way going forward is to change the plugin to support the new way of working!

Yeah, sounds like a nice workaround but still the fix on the plugin is the way to go!

Lets wait for @benct  :)

**Comment by zeridon** [comment]
Pull request that broke stuff: https://github.com/home-assistant/core/pull/54990

**Comment by zeridon** [comment]
note that also buttons are now missing due to `ha-icon-button` no longer using icon

FIX:

```
diff --git a/homeassistant-config/www/xiaomi-vacuum-card.js b/homeassistant-config/www/xiaomi-vacuum-card.js
index 25d6aae..d72ba29 100644
--- a/homeassistant-config/www/xiaomi-vacuum-card.js
+++ b/homeassistant-config/www/xiaomi-vacuum-card.js
@@ -306,9 +306,8 @@
             return data && data.show !== false
                 ? html`<ha-icon-button
                     @click="${() => this.callService(data.service, data.service_data)}"
-                    icon="${data.icon}"
                     title="${data.label || ''}"
-                    style="${this.config.styles.icon}"></ha-icon-button>`
+                    style="${this.config.styles.icon}"><ha-icon style="display:flex;" icon="${data.icon}"></ha-icon></ha-icon-button>`
                 : null;
         }
 ```

**Comment by pannal** [comment]
Yep, definitely broken. Thanks to all of you who hotfixed this with workarounds. Author needs to incorporate the new breaking changes, though :)

**Comment by benct** [comment]
Should be fixed in version `4.4.0`, at least for Xiaomi vacuums (remember to clear browser cache after update)

**Comment by znanywawa** [comment]
Looks like counters for xiaomi are still not working (or there is an issue with Roborock S7):
![image](https://user-images.githubusercontent.com/62244838/140630738-cb576fe9-feb8-40f9-9ab1-fdebdef2608f.png)

Any idea?

**Comment by Tamsy** [comment]
Updated to 4.4.0 through HACS on core-2021.11.1, supervisor-2021.10.8. Activated all deactivated referring entities through Settings --> Integrations --> Xiaomi Miio.

But:
![roborocks5u](https://user-images.githubusercontent.com/6210614/140630972-156c2a25-bd0d-4f5d-9597-85342477cfa0.jpg)


I have 2 Roborock S5 Max devices (2 storey house, one device for each floor). Both are showing the same like the picture above.

**Comment by zeridon** [comment]
add `vendor: xiaomi` to the card config in order to use the new processing of entities

**Comment by StWiesi** [comment]
> Alredy have added vendor, below is my card config: ![image](https://user-images.githubusercontent.com/62244838/140638800-f9b47e55-784c-462b-b458-12dd6c2b2195.png)
> 
> So it doesnt help either.

worked for me. Have you re-enabled all the required entities that were disabled by HA by default after the update?

**Comment by znanywawa** [comment]
> > Alredy have added vendor, below is my card config: ![image](https://user-images.githubusercontent.com/62244838/140638800-f9b47e55-784c-462b-b458-12dd6c2b2195.png)
> > So it doesnt help either.
> 
> worked for me. Have you re-enabled all the required entities that were disabled by HA by default after the update?

Yep, I do have all entities enabled (also, I have disabled and re-enabled them after card update):
![image](https://user-images.githubusercontent.com/62244838/140640321-b6da4195-9c69-4a99-a59f-ae24d880439e.png)

**Comment by znanywawa** [comment]
Alredy have added vendor, below is my card config:
`          - type: custom:xiaomi-vacuum-card
            entity: vacuum.roborock_vacuum_a15
            image: /local/pictures/vacuum/vacuum.png
            name: Roborock S7
            vendor: xiaomi
            attributes:
              mop_attached:
                key: mop_attached
                label: 'Mop: '
              clean_area:
                key: 'clean_area'
                label: 'Cleaned area: '
                unit: ' m2'`

So it doesnt help either.

**Comment by Tamsy** [comment]
Unfortunately same here for the 2 devices (entity is correct):
![vendorxiaomi](https://user-images.githubusercontent.com/6210614/140641752-b2e5618a-94f0-4638-b338-1d102e3e13d6.jpg)

**Comment by pedrolamas** [comment]
> Should be fixed in version `4.4.0`, at least for Xiaomi vacuums (remember to clear browser cache after update)

Working fine here now, no need to use my "hack" anymore! Thank you for the prompt fix! 🙂

**Comment by Heisenberg2980** [comment]
The main card is working now, but the "Customize specific state values" is still not working for me, does anybody know if I can fix it?

```
        - type: custom:xiaomi-vacuum-card
          entity: vacuum.xiaomi_vacuum_cleaner
          image: /local/Floorplan_images/vacuum.png
          name: My Vacuum
          vendor: xiaomi
          buttons:
            spot:
              show: false
          state:
            cleaning_time:
              key: cleaning_time
              label: 'Cleaning time: '
              unit: ' min'
            cleaned_area:
              key: cleaned_area
              label: 'Cleaned area: '
              unit: ' m2'
          attributes:
            total_cleaning_time:
              key: total_cleaning_time
              label: 'Total time: '
              unit: ' min'
            total_cleaned_area:
              key: total_cleaned_area
              label: 'Total area: '
              unit: ' m2'
```
![image](https://user-images.githubusercontent.com/58039006/140643330-faf8481d-4ffb-40f3-985c-83339b286323.png)

**Comment by Bieniu82** [comment]
> It's working now with both vacuums.
> 
> @znanywawa hint made the difference: _"So to fix it, it required to change entity of vacuum device and now card is working as expected."_
still doesn't work for me ... name of the entity is correct, sensors show up values in the entity list, however stay unavailable in the card itself

**Comment by benct** [comment]
If it still does not work, try the following:
- Reload resources through HA
- Hard refresh browser
- Clear browser cache
- Enable new sensors in the xiaomi integration configuration
- The sensors need to be named the same as the vacuum entity and the attribute keys (default). Example:
  - Vacuum entity: `vacuum.some_cool_vacuum`
  - Attribute key: `main_brush_left`
  - Sensor entity: `sensor.some_cool_vacuum_main_brush_left`
- If your vacuum still provide data as attributes, you might need to stay on version 4.3.0 for now.

**Comment by wanti00** [comment]
following

**Comment by Heisenberg2980** [comment]
> The main card is working now, but the "Customize specific state values" is still not working for me, does anybody know if I can fix it?
> 
> ```
>         - type: custom:xiaomi-vacuum-card
>           entity: vacuum.xiaomi_vacuum_cleaner
>           image: /local/Floorplan_images/vacuum.png
>           name: My Vacuum
>           vendor: xiaomi
>           buttons:
>             spot:
>               show: false
>           state:
>             cleaning_time:
>               key: cleaning_time
>               label: 'Cleaning time: '
>               unit: ' min'
>             cleaned_area:
>               key: cleaned_area
>               label: 'Cleaned area: '
>               unit: ' m2'
>           attributes:
>             total_cleaning_time:
>               key: total_cleaning_time
>               label: 'Total time: '
>               unit: ' min'
>             total_cleaned_area:
>               key: total_cleaned_area
>               label: 'Total area: '
>               unit: ' m2'
> ```
> 
> ![image](https://user-images.githubusercontent.com/58039006/140643330-faf8481d-4ffb-40f3-985c-83339b286323.png)

@benct As this issue is closed, should I open a new one for this problem with customize state values?

**Comment by Heisenberg2980** [comment]
Answering my own question, the issue was the name of the entities, I have updated them and it is showing the correct numbers (I just need to figure out if it is possible to change from seconds to minutes or hours, but that is a different issue...):

```
        - type: custom:xiaomi-vacuum-card
          entity: vacuum.xiaomi_vacuum_cleaner
          image: /local/Floorplan_images/vacuum.png
          name: My Vacuum
          vendor: xiaomi
          buttons:
            spot:
              show: false
          state:
            cleaning_time:
              key: last_clean_duration
              label: 'Last clean duration: '
              unit: ' s'
            cleaned_area:
              key: last_clean_area
              label: 'Last clean area: '
              unit: ' m2'
          attributes:
            total_cleaning_time:
              key: total_duration
              label: 'Total time: '
              unit: ' s'
            total_cleaned_area:
              key: total_clean_area
              label: 'Total area: '
              unit: ' m2'
```

![image](https://user-images.githubusercontent.com/58039006/141684941-a739d218-c596-4c15-b622-cce6ec9220fe.png)
