### ISSUE TITLE
Card doesn't show icons anymore! 

### ISSUE THREAD

**Issue by tsloms** [benct/lovelace-xiaomi-vacuum-card#86]
The icons for controlling the vacuum are not displayed anymore.
![Screenshot_20211104-204814](https://user-images.githubusercontent.com/89085152/140409663-a913666e-e998-4c68-91ef-3100ef28a5bc.jpg)
I found out that the reason is that "**ha-icon-button** does not support **icon** anymore, you have to supply the icon SVG path as **path** or use **ha-icon** in the default slot of **ha-icon-button**." 
It's due to this: home-assistant/frontend#10521

**Comment by zeridon** [comment]
quick and dirty fix is to nest a `ha-icon` element where needed (single line)

```
diff --git a/homeassistant-config/www/xiaomi-vacuum-card.js b/homeassistant-config/www/xiaomi-vacuum-card.js
index 25d6aae..d72ba29 100644
--- a/homeassistant-config/www/xiaomi-vacuum-card.js
+++ b/homeassistant-config/www/xiaomi-vacuum-card.js
@@ -306,9 +306,8 @@
             return data && data.show !== false
                 ? html`<ha-icon-button
                     @click="${() => this.callService(data.service, data.service_data)}"
-                    icon="${data.icon}"
                     title="${data.label || ''}"
-                    style="${this.config.styles.icon}"></ha-icon-button>`
+                    style="${this.config.styles.icon}"><ha-icon style="display:flex;" icon="${data.icon}"></ha-icon></ha-icon-button>`
                 : null;
         }
 ```

**Comment by TTLucian** [comment]
Thanks for the fix! Dirty or not, it works

**Comment by tsloms** [comment]
> quick and dirty fix is to nest a `ha-icon` element where needed (single line)
> 
> ```
> diff --git a/homeassistant-config/www/xiaomi-vacuum-card.js b/homeassistant-config/www/xiaomi-vacuum-card.js
> index 25d6aae..d72ba29 100644
> --- a/homeassistant-config/www/xiaomi-vacuum-card.js
> +++ b/homeassistant-config/www/xiaomi-vacuum-card.js
> @@ -306,9 +306,8 @@
>              return data && data.show !== false
>                  ? html`<ha-icon-button
>                      @click="${() => this.callService(data.service, data.service_data)}"
> -                    icon="${data.icon}"
>                      title="${data.label || ''}"
> -                    style="${this.config.styles.icon}"></ha-icon-button>`
> +                    style="${this.config.styles.icon}"><ha-icon style="display:flex;" icon="${data.icon}"></ha-icon></ha-icon-button>`
>                  : null;
>          }
> ```

Maybe I'm stupid, but for me it doesn't work. I replaced the style line and removed the icon line... What am I doing wrong?

**Comment by zeridon** [comment]
@tsloms do a hard refresh (ctrl+r/ctrl+shift+r) i.e. basically do not use cache

**Comment by TTLucian** [comment]
@tsloms delete the ".gz" file (if it exists) from the card's folder, make sure the .js file is the one you modified, change hacstag number in config/dashboard/resources url (1 digit is enough) and it should work. If not, do a hard reload (as suggested above) or restart HA.

**Comment by tsloms** [comment]
Thanks guys, now the controls are back! I appreciate it! 😊

**Comment by zissou1** [comment]
Is this card maintained? Will a fix be released?

**Comment by benct** [comment]
I'll try to get a fix out as soon as I have the time.

**Comment by benct** [comment]
Fixed in version `4.3.0` (might need to clear browser cache after update)

**Comment by Bieniu82** [comment]
icons still not visible :( in 4.4.0
- reloaded the module
- enabled all disabled entities
- reinstalled the module

**Comment by Bieniu82** [comment]
have had it before:

 `      - type: vertical-stack
        title: 'Ad-hoc Cleaning'
        cards:
          - type: 'custom:xiaomi-vacuum-card'
            entity: vacuum.roborock_vacuum
            name: false
            vendor: xiaomi
          - type: entity-button
            name: Vacuum Now
            entity: switch.vacuum_now
            icon: mdi:robot-vacuum
            state_color: true            `

**Comment by sneaker8650** [comment]
![Screenshot 2021-11-07 102908](https://user-images.githubusercontent.com/12570428/140639659-578f0ef5-e24e-4b39-8ec1-fa98de10318d.png)

Card is working fine again, thanks for the fix!

**Comment by Bieniu82** [comment]
have had it before already, still can't see them:

        title: 'Ad-hoc Cleaning'
        cards:
          - type: 'custom:xiaomi-vacuum-card'
            entity: vacuum.roborock_vacuum
            name: false
            vendor: xiaomi
          - type: entity-button
            name: Vacuum Now
            entity: switch.vacuum_now
            icon: mdi:robot-vacuum
            state_color: true

**Comment by zeridon** [comment]
make sure to add `vendor: xiaomi` to the card config (otherwise it will not take the new custom entity pocessing for attributes).
